version: '3.8'

services:
  db:
    image: postgres:15
    restart: unless-stopped
    volumes:
      - postgres_data:/var/lib/postgresql/data
    env_file:
      - ./backend/.env

  backend:
    image: alexsmalldev/alexsmalldev-sead-assignment:backend-latest
    env_file:
      - ./backend/.env
    depends_on:
      - db
    ports:
      - "8000:8000"
    command: daphne -b 0.0.0.0 -p 8000 djangoProject.asgi:application

volumes:
  postgres_data:
