# Generated by Django 5.0.7 on 2024-08-02 17:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('requestAPI', '0004_building'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='building',
            options={'ordering': ['id']},
        ),
    ]
