# Generated by Django 3.2.25 on 2024-08-07 11:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('requestAPI', '0005_alter_building_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='building',
            name='country',
            field=models.CharField(default='United Kingdom', max_length=100),
        ),
    ]
