# Generated by Django 3.2.25 on 2024-08-14 15:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('requestAPI', '0006_alter_building_country'),
    ]

    operations = [
        migrations.DeleteModel(
            name='UserDetails',
        ),
    ]
