# Generated by Django 3.2.25 on 2024-08-14 15:40

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('requestAPI', '0007_delete_userdetails'),
    ]

    operations = [
        migrations.AddField(
            model_name='building',
            name='users',
            field=models.ManyToManyField(related_name='buildings', to=settings.AUTH_USER_MODEL),
        ),
    ]
