# Generated by Django 3.2.25 on 2024-08-21 14:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('requestAPI', '0010_remove_catalogueitem_requires_appointment'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='catalogueitem',
            name='service_image_path',
        ),
    ]
