# Generated by Django 3.2.25 on 2024-08-21 14:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('requestAPI', '0012_catalogueitem_buildings'),
    ]

    operations = [
        migrations.AlterField(
            model_name='catalogueitem',
            name='buildings',
            field=models.ManyToManyField(related_name='catalogueItems', to='requestAPI.Building'),
        ),
    ]
