# Generated by Django 3.2.25 on 2024-08-21 14:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('requestAPI', '0014_auto_20240821_1541'),
    ]

    operations = [
        migrations.RenameField(
            model_name='update',
            old_name='comment',
            new_name='message',
        ),
    ]
