# Generated by Django 3.2.25 on 2024-08-21 14:44

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('requestAPI', '0015_rename_comment_update_message'),
    ]

    operations = [
        migrations.AddField(
            model_name='update',
            name='associated_to',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='associated_updates', to='auth.user'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='update',
            name='created_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='created_updates', to=settings.AUTH_USER_MODEL),
        ),
    ]
