# Generated by Django 3.2.25 on 2024-08-21 14:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('requestAPI', '0016_auto_20240821_1544'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='catalogueitem',
            name='service_icon_path',
        ),
        migrations.AddField(
            model_name='catalogueitem',
            name='service_icon',
            field=models.ImageField(blank=True, null=True, upload_to='service_icons/'),
        ),
    ]
