# Generated by Django 3.2.25 on 2024-08-28 10:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('requestAPI', '0017_auto_20240821_1548'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='catalogueitem',
            name='buildings',
        ),
    ]
