# Generated by Django 5.0.7 on 2024-08-28 17:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('requestAPI', '0018_remove_catalogueitem_buildings'),
    ]

    operations = [
        migrations.AddField(
            model_name='servicerequest',
            name='priority',
            field=models.CharField(choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High')], default='low', max_length=20),
        ),
        migrations.AddField(
            model_name='servicerequest',
            name='severity',
            field=models.CharField(choices=[('minor', 'Minor'), ('major', 'Major'), ('critical', 'Critical')], default='minor', max_length=20),
        ),
    ]
