# Generated by Django 5.0.7 on 2024-08-29 20:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('requestAPI', '0020_remove_servicerequest_severity'),
    ]

    operations = [
        migrations.AddField(
            model_name='servicerequest',
            name='building',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='requestAPI.building'),
        ),
        migrations.AlterField(
            model_name='servicerequest',
            name='customer_notes',
            field=models.TextField(blank=True, null=True),
        ),
    ]
