# Generated by Django 5.0.7 on 2024-08-29 20:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('requestAPI', '0021_servicerequest_building_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='servicerequest',
            name='title',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
