# Generated by Django 5.0.7 on 2024-08-29 21:46

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('requestAPI', '0025_alter_servicerequest_service_level_agreement_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='servicerequest',
            name='service_level_agreement_date',
            field=models.DateTimeField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
