# Generated by Django 5.0.7 on 2024-08-29 22:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('requestAPI', '0027_alter_servicerequest_service_level_agreement_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='servicerequest',
            name='status',
            field=models.CharField(choices=[('open', 'Open'), ('in_progress', 'In Progress'), ('completed', 'completed')], default='open', max_length=20),
        ),
    ]
