# Generated by Django 5.0.7 on 2024-09-03 22:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('requestAPI', '0029_alter_servicerequest_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='update',
            name='type',
            field=models.TextField(choices=[('message', 'Message'), ('event', 'Event')], default='event', max_length=100),
        ),
        migrations.AlterField(
            model_name='servicerequest',
            name='status',
            field=models.CharField(choices=[('open', 'Open'), ('in_progress', 'In Progress'), ('completed', 'Completed'), ('cancelled', 'Cancelled')], default='open', max_length=20),
        ),
    ]
