# Generated by Django 3.2.25 on 2024-09-10 09:55

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('requestAPI', '0032_rename_catalogueitem_servicetype'),
    ]

    operations = [
        migrations.AlterField(
            model_name='building',
            name='users',
            field=models.ManyToManyField(blank=True, null=True, related_name='buildings', to=settings.AUTH_USER_MODEL),
        ),
    ]
