# Generated by Django 3.2.25 on 2024-09-10 11:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('requestAPI', '0034_auto_20240910_1059'),
    ]

    operations = [
        migrations.AlterField(
            model_name='servicetype',
            name='service_icon',
            field=models.ImageField(blank=True, upload_to='service_icons/'),
        ),
    ]
