# Generated by Django 3.2.25 on 2024-09-11 12:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('requestAPI', '0035_alter_servicetype_service_icon'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='building',
            options={},
        ),
    ]
