# Generated by Django 3.2.25 on 2024-09-12 14:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('requestAPI', '0037_servicerequest_following_users'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='servicerequest',
            name='following_users',
        ),
    ]
