# Generated by Django 3.2.25 on 2024-09-22 14:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('requestAPI', '0044_auto_20240920_1414'),
    ]

    operations = [
        migrations.AlterField(
            model_name='servicerequest',
            name='created_date',
            field=models.DateTimeField(blank=True),
        ),
    ]
